# Generated by Django 4.0.3 on 2022-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cachedFile',
            fields=[
                ('fileQueryName', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('cached', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
