# Generated by Django 4.0.3 on 2022-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0004_cachedfile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
