# Generated by Django 4.0.3 on 2022-05-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0005_cachedfile_size_storedfile_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeredInstance',
            fields=[
                ('ipv4', models.CharField(max_length=15)),
                ('total_memory', models.BigIntegerField(default=0)),
                ('used_memory', models.BigIntegerField(default=0)),
                ('stored_files_size', models.BigIntegerField(default=0)),
                ('cached_files_size', models.BigIntegerField(default=0)),
                ('instance_name', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('stored_files_count', models.IntegerField(default=0)),
                ('cached_files_count', models.IntegerField(default=0)),
                ('uptime', models.BigIntegerField(default=0)),
                ('last_health_check', models.DateTimeField(auto_now=True)),
                ('healthy', models.BooleanField(default=True)),
            ],
        ),
    ]
