# Generated by Django 4.0.3 on 2022-05-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0006_registeredinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='presignedURL',
            fields=[
                ('signature', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('expires', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shared.storedfile')),
            ],
        ),
    ]
