# Generated by Django 4.0.3 on 2022-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shared', '0008_ipv4access'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedfile',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
